name: Publish

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [main]

env:
  IMAGE_NAME: movie-manager

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew bootBuildImage

    - name: Docker push
      run: |
        VERSION=$(./gradlew -q printVersionName)
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker image tag $IMAGE_NAME:$VERSION $DOCKER_USERNAME/$IMAGE_NAME:$VERSION
        docker push $DOCKER_USERNAME/$IMAGE_NAME:$VERSION
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
